<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip3 install seaborn
!pip install openpyxl

zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/gabrielomarperezhernandez/Library/Python/3.14/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/gabrielomarperezhernandez/Library/Python/3.14/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/gabrielomarperezhernandez/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
zsh:1: command not found: pip

In [12]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

CARGA DE ARCHIVO XLSX

In [13]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Telefono                                  2 non-null        str
 4   Estatus de Lead                           654 non-null      object
 5   Potencial de compra                       614 non-null      object
 6   PDM                                       1048574 non-null  float64
 7   SDC                                       1048573 non-null  float64
 8   Venta                                     1048570 non-null  float64
 9   Asesor Asignado                           656 non-null      str
 10  ¿Por que no ha visitado la agencia?       493 non-null      str
 11  ¿Por que no hay solicitud de credito?     379 non-null      str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 13  ¿Por que no hubo proceso wow?             364 non-null      str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null      str
 15  Unnamed: 15                               16 non-null       str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 129.0+ MB

In [14]:
#Filtro por filas
#filtro1= df.iloc[3:10,: ]           #Filas consecutivas
#filtro1=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
#filtro1= df.iloc[ [0] + list(range(10, 14)) + [50] , [0, 1] ]  #Filas combinadas
filtro1= df.iloc[0:673,: ]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           638 non-null    object
 5   Potencial de compra                       599 non-null    object
 6   PDM                                       672 non-null    float64
 7   SDC                                       671 non-null    float64
 8   Venta                                     668 non-null    float64
 9   Asesor Asignado                           641 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 84.3+ KB

In [15]:
#Filtro por columnas
#filtro2=df.iloc[ : , 0:3]       #Columnas consecutivas
#filtro2=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas
#filtro2= df.iloc[ :, list(range(1, 6)) + 9]  #Filas combinadas
filtro2 = df.iloc[ : , list(range(0, 3))+ list(range(4, 15))] #En los rangos se debe colocar +1 del limite superior
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Estatus de Lead                           654 non-null      object
 4   Potencial de compra                       614 non-null      object
 5   PDM                                       1048574 non-null  float64
 6   SDC                                       1048573 non-null  float64
 7   Venta                                     1048570 non-null  float64
 8   Asesor Asignado                           656 non-null      str
 9   ¿Por que no ha visitado la agencia?       493 non-null      str
 10  ¿Por que no hay solicitud de credito?     379 non-null      str
 11  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 12  ¿Por que no hubo proceso wow?             364 non-null      str
 13  ¿Por que se asigno antes de vistar piso?  353 non-null      str
dtypes: datetime64[us](1), float64(3), object(4), str(6)
memory usage: 112.0+ MB

In [16]:
#Filtro por filas y columnas
#filtro3=df.iloc[ : , [0,1,2,4,5,6,7,8,9]] # Forma equivalente
filtro3 = df.iloc[ 0:673 , list(range(0, 3))+ list(range(4, 15))] 
filtro3.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 14 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Estatus de Lead                           638 non-null    object
 4   Potencial de compra                       599 non-null    object
 5   PDM                                       672 non-null    float64
 6   SDC                                       671 non-null    float64
 7   Venta                                     668 non-null    float64
 8   Asesor Asignado                           641 non-null    str
 9   ¿Por que no ha visitado la agencia?       493 non-null    str
 10  ¿Por que no hay solicitud de credito?     379 non-null    str
 11  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 12  ¿Por que no hubo proceso wow?             364 non-null    str
 13  ¿Por que se asigno antes de vistar piso?  353 non-null    str
dtypes: datetime64[us](1), float64(3), object(4), str(6)
memory usage: 73.7+ KB

In [17]:
#Convertir archivo filtrado a CSV
filtro3.to_csv("Citas_Digital_Filtrado.csv", index=False)

In [18]:
#Leemos el archivo filtrado para convertirlo en Dataframe
df_filtrado= pd.read_csv("Citas_Digital_Filtrado.csv")
df_filtrado.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 14 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    str
 1   Fecha                                     72 non-null     str
 2   Nombre Cliente                            652 non-null    str
 3   Estatus de Lead                           638 non-null    str
 4   Potencial de compra                       599 non-null    str
 5   PDM                                       672 non-null    float64
 6   SDC                                       671 non-null    float64
 7   Venta                                     668 non-null    float64
 8   Asesor Asignado                           641 non-null    str
 9   ¿Por que no ha visitado la agencia?       493 non-null    str
 10  ¿Por que no hay solicitud de credito?     379 non-null    str
 11  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 12  ¿Por que no hubo proceso wow?             364 non-null    str
 13  ¿Por que se asigno antes de vistar piso?  353 non-null    str
dtypes: float64(3), str(11)
memory usage: 73.7 KB

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [19]:
#Filtro por objeto
filtro4=df_filtrado[df_filtrado["Asesor Asignado"] == "Nancy"]
filtro4

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
8,Saul,NaN,Jacinto,Finalizado,0.8,0.0,0.0,0.0,Nancy,No ha visitado la agencia por temas de trabajo,"Se esta trabajando en ello, sin embargo el cli...",Por que no ha visitado la agencia,Por parte de BDC siempre se es cortes y amable,Se asgino antes por recomendacion de Gerencia ...
41,Saul,NaN,Ulises Alejo,Finalizado,0.8,1.0,0.0,0.0,Nancy,Ya visito la agencia el dia domingo 11,Ya se paso a precalificar,Si hizo prueba de manejo y le encanto la unidad,Recibio la atencion,Se asigno hasta el momento de la visita
49,Antonio,NaN,Diego Cabrejiz,Activo,0.8,1.0,0.0,1.0,Nancy,Ya visito la agencia,Sera compra de contado,Ya realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
275,Ana,NaN,"Miriam Lizbeth Ruiz, Zamudio",Activo,0.85,0.0,1.0,0.0,Nancy,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
340,Ana,NaN,"Gloria Elena Benavides,",Activo,0.8,0.0,1.0,0.0,Nancy,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
353,Ana,NaN,Sr. Roberto Loeza\n,Activo,0.6,0.0,1.0,0.0,Nancy,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
367,Antonio,NaN,Andy,Activo,0.8,1.0,0.0,0.0,Nancy,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
368,Antonio,NaN,Hugo,Activo,0.8,1.0,0.0,0.0,Nancy,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita

In [22]:
#Leemos el archivo filtrado para convertirlo en Dataframe con indice
df_filtrado_indice= pd.read_csv("Citas_Digital_Filtrado.csv", index_col=8)
df_filtrado_indice

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
Asesor Asignado,,,,,,,,,,,,,
Nancy,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
Victor,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
Alan,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
Mauricio,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
Mauricio,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mario Varela,Ignacio,2026-07-21,Carlos Balderrama,Activo,0.5,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
Mauricio,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,0.5,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
Aurelio,Ana,2026-07-22,Arat Israel,Activo,80&,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
Pedro Antonio,Ana,2026-07-22,Maira Escalante,Activo,0.8,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
Aurelio,Ignacio,2026-07-22,Zaira Macip,Activo,0.5,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [23]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro5=df_filtrado_indice.loc[["Nancy","Alan"], ["¿Por que no hubo prueba de manejo ?"]]
filtro5

                              ¿Por que no hubo prueba de manejo ?
Asesor Asignado
Nancy                                  Si, hizo prueba de manejo
Nancy                          Por que no ha visitado la agencia
Nancy            Si hizo prueba de manejo y le encanto la unidad
Nancy                                 Ya realizo prueba de manejo
Nancy                                 Ya realizo prueba de manejo
Nancy                                 Ya realizo prueba de manejo
Nancy                                 Ya realizo prueba de manejo
Nancy                                 Ya realizo prueba de manejo
Nancy                                 Ya realizo prueba de manejo
Alan                                    Realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                              Si realizo la prueba de manejo
Alan                                      Llego al cierre del dia
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                             FORANEA VERACRUZ
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo
Alan                                  Ya realizo prueba de manejo
Alan                                                          NaN
Alan                                  Ya realizo prueba de manejo

In [21]:
#Filtro por cabecera
filtro6=df_filtrado.head(6)
filtro6

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
5,Saul,NaN,Antonio,Activo,0.85,1.0,1.0,0.0,Mauricio,Visito la agencia el dia 13 de abril,Si hubo solicitud de credito,Si realizo prueba de manejo,"Lo resivio por parte del asesor, ya que el dia...",Se asigno hasta que visitara Piso

In [24]:
#Filtro de cola
filtro7=df_filtrado.tail(6)
filtro7

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
667,Ana,2026-07-16,Margaret Silva Serrano,Activo,0.8,1.0,0.0,0.0,Nayeli,NaN,NaN,NaN,NaN,NaN
668,Ignacio,2026-07-21,Carlos Balderrama,Activo,0.5,1.0,1.0,1.0,Mario Varela,NaN,NaN,NaN,NaN,NaN
669,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,0.5,0.0,0.0,0.0,Mauricio,NaN,NaN,NaN,NaN,NaN
670,Ana,2026-07-22,Arat Israel,Activo,80&,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
671,Ana,2026-07-22,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [26]:
#Filtro por comparacion
filtro8=df_filtrado[df_filtrado["Potencial de compra"] < 0.5]
filtro8

TypeError: '<' not supported between instances of 'str' and 'float'

In [27]:
#Conversión de tipo de dato de columna de tipo String a Float
df_filtrado['Potencial de compra']= df_filtrado['Potencial de compra'].astype(float)

ValueError: could not convert string to float: 'Ventas '

In [ ]:
#Reemplazo de datos de una columna 
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("Ventas ","0", regex=False)

In [ ]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("%","", regex=False)

In [ ]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("'","", regex=False)

In [ ]:
df_filtrado['Potencial de compra']=df_filtrado['Potencial de compra'].str.replace("&","", regex=False)

**FILTROS BASICOS CON CONETORES LOGICOS**

In [ ]:
#Filtro Y
filtro9=df_filtrado[(df_filtrado["Potencial de compra"] >= 0.9) & (df_filtrado["Asesor Asignado"] == "Aurelio")]
filtro9

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
233,Antonio,NaN,Rogelio Hernandez,Activo,0.95,1.0,1.0,1.0,Aurelio,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
267,Ana,NaN,Diego Martinez,Activo,0.90,0.0,0.0,0.0,Aurelio,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
435,Antonio,NaN,Sergio ortega,Activo,0.90,1.0,1.0,1.0,Aurelio,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
594,Ana,NaN,Juan Roque,Activo,1.00,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
670,Ana,2026-07-22,Arat Israel,Activo,80.00,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Filtro o
filtro10=df_filtrado[(df_filtrado["Potencial de compra"] < 0.2) | (df_filtrado["BDC "] == "Saul")]
filtro10

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
32,Saul,NaN,13,11,0.00,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Saul,NaN,Francisco Santander,Finalizado,0.90,1.0,0.0,0.0,Alan,Nos visito el dia 08 de junio,Pretende compra de contado,Realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
72,Antonio,NaN,Jaime Juarez,Acitvo,0.05,1.0,1.0,0.0,Mauricio,Ya visito la agencia,Ya esta pre aprobado,Ya realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
82,Saul,NaN,Jose Miguel,Activo,0.70,1.0,0.0,0.0,Mauricio,Ya nos visito el dia 27 de junio,En proceso,Ya realizo la prueba de manejo,Si recibio la atencion,se asigno hasta la visita de piso
94,Saul,NaN,Anthony,Activo,0.80,1.0,1.0,0.0,Nos visita el sabado 5,Ya nos visito,Ya esta la solicitud,Ya realizo la prueba de manejo,Esta en proceso,NaN
100,Saul,NaN,Roberto Paz Rojano,Activo,0.80,0.0,0.0,0.0,Aurelio,Ya nos visito el dia 15 Julio,Ya esta en proceso,El cliente comenta que no queria manejar la un...,Recibio la atencion,Se asigna en la visita
105,Saul,NaN,Karla,Activo,NaN,0.0,0.0,0.0,Ignacio,Ya visito la agencia,Ya esta en proceso,Ya realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
113,Saul,NaN,Gustavo Rojas Garcia,Activo,0.80,1.0,1.0,0.0,Victor,Ya visito la agencia,Si hay solicitud de credito,Ya realizo prueba de manejo,Recibio la atencion,Se asigna en la visita
114,Saul,NaN,Mauricio Garcia,Activo,80.00,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#Filtro not
filtro11=df_filtrado[~(df_filtrado["BDC "] == "Antonio")]
filtro11

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,Ignacio,2026-07-21,Carlos Balderrama,Activo,0.5,1.0,1.0,1.0,Mario Varela,NaN,NaN,NaN,NaN,NaN
669,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,0.5,0.0,0.0,0.0,Mauricio,NaN,NaN,NaN,NaN,NaN
670,Ana,2026-07-22,Arat Israel,Activo,80&,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
671,Ana,2026-07-22,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN

In [29]:
#Convertir archivo filtrado a CSV
filtro11.to_csv("filtro11.csv", index=False)

In [30]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("filtro11.csv")

ModuleNotFoundError: No module named 'google'